services:
  db:
    image: postgres:latest
    container_name: local_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - ./local-postgres-data:/var/lib/postgresql/data

networks:
  pg-network:
    driver: bridge